# Generated by Django 6.0.3 on 2026-03-21 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=50)),
                ('schedule_text', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.academicterm')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.AutoField(primary_key=True, serialize=False)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.CharField(blank=True, max_length=20, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.classschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_logged', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='GradingComponent',
            fields=[
                ('component_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('weight_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.classschedule')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('total_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('date_given', models.DateField(blank=True, null=True)),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.period')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.gradingcomponent')),
            ],
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.enrollment')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherSchedule',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=100)),
                ('room', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
